#if os(iOS) || os(tvOS)
@_spi(Internals) import SnapshotTesting
import Foundation
import SwiftUI
import UIKit

@MainActor
enum SnapshotHelper {

    /// Determines the record mode from the `SNAPSHOT_RECORD` environment variable.
    ///
    /// Set `SNAPSHOT_RECORD=1` or `SNAPSHOT_RECORD=all` to re-record every snapshot.
    /// Set `SNAPSHOT_RECORD=missing` to record only missing snapshots.
    /// When unset or empty the caller-supplied `record` parameter is used as-is.
    private static var environmentRecordMode: SnapshotTestingConfiguration.Record? = {
        guard let value = ProcessInfo.processInfo.environment["SNAPSHOT_RECORD"]?.lowercased(),
              !value.isEmpty
        else { return nil }
        switch value {
        case "1", "true", "all": return .all
        case "missing": return .missing
        case "failed": return .failed
        case "0", "false", "never": return .never
        default: return nil
        }
    }()

    /// Wraps a SwiftUI view in a UIHostingController configured for snapshot testing.
    static func hostingController<V: View>(
        for view: V,
        interfaceStyle: UIUserInterfaceStyle = .light
    ) -> UIHostingController<V> {
        let controller = UIHostingController(rootView: view)
        controller.overrideUserInterfaceStyle = interfaceStyle
        return controller
    }

    /// Asserts a snapshot with an explicit `snapshotDirectory` computed from `#filePath`.
    ///
    /// Workaround for SnapshotTesting path resolution issues when test sources
    /// live inside SPM packages but the test target is generated by XcodeGen.
    /// See: https://github.com/pointfreeco/swift-snapshot-testing/discussions/553
    static func assertSnapshot<Value, Format>(
        of value: @autoclosure () throws -> Value,
        as snapshotting: Snapshotting<Value, Format>,
        named name: String? = nil,
        record: SnapshotTestingConfiguration.Record? = nil,
        timeout: TimeInterval = 5,
        fileID: StaticString = #fileID,
        file filePath: StaticString = #filePath,
        testName: String = #function,
        line: UInt = #line,
        column: UInt = #column
    ) {
        let fileUrl = URL(fileURLWithPath: "\(filePath)", isDirectory: false)
        let fileName = fileUrl.deletingPathExtension().lastPathComponent
        let snapshotDir = fileUrl
            .deletingLastPathComponent()
            .appendingPathComponent("__Snapshots__")
            .appendingPathComponent(fileName)
            .path

        // Environment variable overrides the caller-supplied record parameter.
        let effectiveRecord = Self.environmentRecordMode ?? record

        let failure = verifySnapshot(
            of: try value(),
            as: snapshotting,
            named: name,
            record: effectiveRecord,
            snapshotDirectory: snapshotDir,
            timeout: timeout,
            fileID: fileID,
            file: filePath,
            testName: testName,
            line: line,
            column: column
        )
        guard let message = failure else { return }
        if let effectiveRecord, effectiveRecord != .never {
            return
        }
        recordIssue(
            message,
            fileID: fileID,
            filePath: filePath,
            line: line,
            column: column
        )
    }
}

#endif // os(iOS) || os(tvOS)
