name: Update Version Badge

on:
  push:
    tags: ['v*']

jobs:
  badge:
    runs-on: ubuntu-latest
    steps:
      - name: Update version badge
        uses: schneegans/dynamic-badges-action@0e50b8bad39e7e1afd3e4e9c2b7dd145fad07501 # v1.8.0
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gistID: 1b309b73189be09d6e6a1a163c7693e6
          filename: miryam-version.json
          label: version
          message: ${{ github.ref_name }}
          color: blue
